[package]
name = "sim"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {workspace = true}
execution-data = { path = "../execution-data" }
executor = { path = "../executor" }
bevy_rapier3d = { workspace = true }
bevy = { workspace = true }
bevy_editor_cam = { workspace = true }
