[workspace]

resolver = "2"

members = [
    "execution-data", "executor", "sim",
]

exclude = [
    "sample-robot-code", "bevy-experiment",
]

[workspace.dependencies]
clap = { version = "3.1.15", features = ["derive"] }
anyhow = "1.0.99"
rapier3d = { version = "0.28.0", features = [ "simd-stable" ] }
wasmtime = "36.0.2"
